[build]
  publish = "dist" # Adjust this if your build directory is different
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"

[headers.values]
  Cache-Control = "no-cache, no-store, must-revalidate"
  Pragma = "no-cache"
  Expires = "0"